#!/bin/tcsh -f
#PBS -S /bin/tcsh
#PBS -j oe
#PBS -q para
#PBS -l nodes=1:ppn=5
#PBS -l walltime=01:00:00
#
cd /net/para33/data2/hendrix/git/neural_deprojection/neural_deprojection/models/identify_medium_SCD/
setenv PATH /net/para33/data2/hendrix/git/neural_deprojection/neural_deprojection/models/identify_medium_SCD/
#
/net/para33/data2/hendrix/git/neural_deprojection/neural_deprojection/models/identify_medium_SCD/para_script.sh