#!/bin/bash

qsub  /net/para33/data2/hendrix/git/neural_deprojection/neural_deprojection/models/identify_medium_SCD/para_script.sh \
    -N "data_maker" \
    -q para \
    -l nodes=1:ppn=32 \
    -l walltime=1:00:00 \
    -l mem=10GB \
    -e ./ \
    -o ./